spring:
  application:
    name: com.spring_data_jpa
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_jpa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 9876
